"""Core module for stepper motor control.

This module provides the core functionality for stepper motors serial communication.

It includes constants, parameter classes, and exception handling for motor control operations.

Example:
    from stepper.core import DeviceParams, Speed, Direction

    # Create device parameters
    device = DeviceParams(port="COM4", baudrate=115200)

    # Configure movement parameters
    speed = Speed(1500)  # 1500 RPM
    direction = Direction.CW  # Clockwise rotation
"""

from .constants import (
    AbsoluteFlag,
    Acceleration,
    Address,
    AutoHoming,
    BaudRate,
    CanRate,
    ChecksumMode,
    ClosedLoopCurrent,
    CommunicationMode,
    ControlMode,
    CurrentUnit,
    DefaultDir,
    Direction,
    EnableFlag,
    EnableLevel,
    EnablePin,
    HomingMode,
    InductanceUnit,
    Kpid,
    LoopMode,
    MaxVoltage,
    Microstep,
    MicrostepInterp,
    MotorType,
    OnTargetWindow,
    OpenLoopCurrent,
    PulseCount,
    ResistanceUnit,
    ResponseMode,
    ScreenOff,
    Speed,
    SpeedReduction,
    SpeedUnit,
    StallCurrent,
    StallProtect,
    StallSpeed,
    StallTime,
    StoreFlag,
    SyncFlag,
    SystemConstants,
    TimeUnit,
    VoltageUnit,
)
from .exceptions import (
    CommandError,
    CommunicationError,
    MotorError,
    StatusError,
    ValidationError,
)
from .parameters import (
    BusVoltageParams,
    ConfigParams,
    DeviceParams,
    EncoderParams,
    HomingParams,
    HomingStatus,
    JogParams,
    MotorRHParams,
    OpenLoopTargetPositionParams,
    PhaseCurrentParams,
    PIDParams,
    PositionErrorParams,
    PositionParams,
    PulseCountParams,
    Readables,
    RealTimePositionParams,
    RealTimeSpeedParams,
    StartSpeedParams,
    StepperStatus,
    SystemParams,
    TargetPositionParams,
    VersionParams,
    Writables,
)

__all__ = [
    # Constants
    "Address",
    "Direction",
    "Speed",
    "Acceleration",
    "PulseCount",
    "AbsoluteFlag",
    "HomingMode",
    "EnablePin",
    "SystemConstants",
    "BaudRate",
    "ControlMode",
    "LoopMode",
    "Microstep",
    "OpenLoopCurrent",
    "StallCurrent",
    "StallTime",
    "AutoHoming",
    "CanRate",
    "ChecksumMode",
    "ClosedLoopCurrent",
    "CommunicationMode",
    "CurrentUnit",
    "DefaultDir",
    "EnableFlag",
    "EnableLevel",
    "InductanceUnit",
    "Kpid",
    "MaxVoltage",
    "MicrostepInterp",
    "MotorType",
    "OnTargetWindow",
    "ResistanceUnit",
    "ResponseMode",
    "ScreenOff",
    "SpeedReduction",
    "SpeedUnit",
    "StallProtect",
    "StallSpeed",
    "StoreFlag",
    "SyncFlag",
    "TimeUnit",
    "VoltageUnit",
    # Exceptions
    "MotorError",
    "CommandError",
    "ValidationError",
    "CommunicationError",
    "StatusError",
    # Parameters
    "DeviceParams",
    "JogParams",
    "PositionParams",
    "HomingParams",
    "ConfigParams",
    "PIDParams",
    "SystemParams",
    "StepperStatus",
    "HomingStatus",
    "StartSpeedParams",
    "BusVoltageParams",
    "EncoderParams",
    "MotorRHParams",
    "OpenLoopTargetPositionParams",
    "PhaseCurrentParams",
    "PositionErrorParams",
    "PulseCountParams",
    "RealTimePositionParams",
    "RealTimeSpeedParams",
    "Readables",
    "TargetPositionParams",
    "VersionParams",
    "Writables",
]
